---
repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        name: CMake Format
        entry: cmake-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.0
    hooks:
      - id: clang-format
        args: [-i,--style=file]
        exclude: '.*\.json'
  - repo: https://github.com/cisagov/pre-commit-shfmt
    rev: v0.0.2
    hooks:
      - id: shfmt
        name: shfmt bash formatting
        args: ["-i=2", "-ci"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.json$
        args: ["--write"]
        name: "json-formatting-prettier"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace